version: '3'
services:
  api:
    build: .
    ports:
      - "8001:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
